import uuid
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("production", "0001_initial"),
        ("warehouse", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardCost",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("cost_period_start", models.DateField()),
                ("cost_period_end", models.DateField()),
                ("raw_material_cost_per_kg", models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal("0"))])),
                ("labor_cost_per_kg", models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal("0"))])),
                ("overhead_cost_per_kg", models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal("0"))])),
                ("energy_cost_per_kg", models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal("0"))])),
                ("total_standard_cost_per_kg", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=14)),
                ("notes", models.TextField(blank=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_standard_costs", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="standardcost_created", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="standardcost_updated", to=settings.AUTH_USER_MODEL)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="standard_costs", to="warehouse.product")),
            ],
            options={"db_table": "analytics_standard_costs", "ordering": ["-cost_period_start"], "verbose_name": "Standard Cost", "verbose_name_plural": "Standard Costs"},
        ),
        migrations.AddIndex(
            model_name="standardcost",
            index=models.Index(fields=["cost_period_start", "cost_period_end"], name="analytics_stdcost_period_idx"),
        ),
        migrations.CreateModel(
            name="ActualCost",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("cost_date", models.DateField(db_index=True)),
                ("raw_material_cost_uzs", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("labor_cost_uzs", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("overhead_cost_uzs", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("energy_cost_uzs", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("maintenance_cost_uzs", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("waste_cost_uzs", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("total_cost_uzs", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("quantity_kg", models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.001"))])),
                ("cost_per_kg", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=14)),
                ("notes", models.TextField(blank=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="actualcost_created", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="actualcost_updated", to=settings.AUTH_USER_MODEL)),
                ("production_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="actual_costs", to="production.productionorder")),
                ("production_batch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="actual_costs", to="production.productionbatch")),
            ],
            options={"db_table": "analytics_actual_costs", "ordering": ["-cost_date"], "verbose_name": "Actual Cost", "verbose_name_plural": "Actual Costs"},
        ),
        migrations.AddIndex(
            model_name="actualcost",
            index=models.Index(fields=["cost_date"], name="analytics_actualcost_date_idx"),
        ),
        migrations.CreateModel(
            name="ProfitabilityAnalysis",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("analysis_date", models.DateField(db_index=True)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("revenue_uzs", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("cogs_uzs", models.DecimalField(decimal_places=2, default=Decimal("0"), help_text="Cost of Goods Sold", max_digits=18)),
                ("gross_profit_uzs", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("gross_margin_pct", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=7)),
                ("overhead_allocated_uzs", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("net_profit_uzs", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("net_margin_pct", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=7)),
                ("quantity_kg", models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=12)),
                ("revenue_per_kg", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=14)),
                ("notes", models.TextField(blank=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="profitabilityanalysis_created", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="profitabilityanalysis_updated", to=settings.AUTH_USER_MODEL)),
                ("production_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="profitability_analyses", to="production.productionorder")),
            ],
            options={"db_table": "analytics_profitability", "ordering": ["-analysis_date"], "verbose_name": "Profitability Analysis", "verbose_name_plural": "Profitability Analyses"},
        ),
        migrations.AddIndex(
            model_name="profitabilityanalysis",
            index=models.Index(fields=["analysis_date"], name="analytics_profit_date_idx"),
        ),
        migrations.CreateModel(
            name="ProductionKPI",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("kpi_date", models.DateField(db_index=True)),
                ("shift", models.CharField(blank=True, max_length=20)),
                ("output_kg", models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=12)),
                ("target_kg", models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=12)),
                ("efficiency_pct", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=7)),
                ("quality_pass_rate_pct", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=7)),
                ("waste_pct", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=7)),
                ("downtime_hours", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=6)),
                ("cost_per_kg", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("oee_pct", models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ("energy_kwh", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="productionkpi_created", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="productionkpi_updated", to=settings.AUTH_USER_MODEL)),
                ("production_line", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="kpis", to="production.productionline")),
            ],
            options={"db_table": "analytics_production_kpi", "ordering": ["-kpi_date"], "verbose_name": "Production KPI", "verbose_name_plural": "Production KPIs"},
        ),
        migrations.AddConstraint(
            model_name="productionkpi",
            constraint=models.UniqueConstraint(fields=["production_line", "kpi_date", "shift"], name="analytics_kpi_line_date_shift_uniq"),
        ),
        migrations.AddIndex(
            model_name="productionkpi",
            index=models.Index(fields=["kpi_date"], name="analytics_kpi_date_idx"),
        ),
        migrations.CreateModel(
            name="ProductionForecast",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("forecast_date", models.DateField(help_text="Date when forecast was recorded")),
                ("period", models.CharField(choices=[("weekly", "Weekly"), ("monthly", "Monthly"), ("quarterly", "Quarterly")], max_length=20)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("forecast_quantity_kg", models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0"))])),
                ("actual_quantity_kg", models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ("forecast_accuracy_pct", models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ("confidence_low_kg", models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ("confidence_high_kg", models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ("method", models.CharField(choices=[("moving_average", "Moving Average"), ("linear_regression", "Linear Regression"), ("manual", "Manual")], default="manual", max_length=30)),
                ("notes", models.TextField(blank=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="productionforecast_created", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="productionforecast_updated", to=settings.AUTH_USER_MODEL)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="forecasts", to="warehouse.product")),
            ],
            options={"db_table": "analytics_forecasts", "ordering": ["-forecast_date", "-period_start"], "verbose_name": "Production Forecast", "verbose_name_plural": "Production Forecasts"},
        ),
        migrations.AddIndex(
            model_name="productionforecast",
            index=models.Index(fields=["period_start", "period_end"], name="analytics_forecast_period_idx"),
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("widget_type", models.CharField(choices=[("kpi_card", "KPI Card"), ("bar_chart", "Bar Chart"), ("line_chart", "Line Chart"), ("pie_chart", "Pie Chart"), ("table", "Table"), ("metric", "Metric")], max_length=20)),
                ("title", models.CharField(max_length=200)),
                ("config", models.JSONField(default=dict, help_text="Widget-specific config: data source, filters, chart type")),
                ("position_x", models.PositiveSmallIntegerField(default=0)),
                ("position_y", models.PositiveSmallIntegerField(default=0)),
                ("width", models.PositiveSmallIntegerField(default=2)),
                ("height", models.PositiveSmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="dashboardwidget_created", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="dashboardwidget_updated", to=settings.AUTH_USER_MODEL)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dashboard_widgets", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "analytics_dashboard_widgets", "ordering": ["position_y", "position_x"], "verbose_name": "Dashboard Widget", "verbose_name_plural": "Dashboard Widgets"},
        ),
    ]
