# Generated by Django 5.0.6 on 2026-05-22 04:36

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cotton_production", "0002_alter_cottonbatch_created_by_and_more"),
        ("tolling", "0002_alter_tollingcontract_created_by_and_more"),
        ("warehouse", "0003_add_tolling_warehouse_types"),
        ("yarn_production", "0003_yarnbatch_tolling_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("ginning", "Paxta Tozalash / Cotton Ginning"),
                            ("spinning", "Ip Yigiruv / Yarn Spinning"),
                            ("blending", "Aralashtirish / Blending"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "factory",
                    models.CharField(
                        choices=[
                            ("paxta_zavodi", "Paxta Tozalash Zavodi"),
                            ("ip_zavodi", "Ip Yigiruv Zavodi"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "equipment_model",
                    models.CharField(
                        blank=True, help_text="e.g. Rieter R60", max_length=200
                    ),
                ),
                (
                    "capacity_per_hour",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="kg/hour",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("installation_date", models.DateField(blank=True, null=True)),
                (
                    "maintenance_schedule",
                    models.CharField(
                        blank=True, help_text="weekly / monthly", max_length=50
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ishlab chiqarish liniyasi",
                "verbose_name_plural": "Ishlab chiqarish liniyalari",
                "db_table": "production_lines",
                "ordering": ["factory", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductionOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "order_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("direct", "To'g'ridan sotish / Direct Sale"),
                            ("tolling", "Davalliq / Tolling"),
                            ("state", "Davlat buyurtmasi / State Order"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qoralama / Draft"),
                            ("approved", "Tasdiqlangan / Approved"),
                            ("in_progress", "Jarayonda / In Progress"),
                            ("completed", "Yakunlangan / Completed"),
                            ("cancelled", "Bekor qilingan / Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "input_quantity_kg",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                (
                    "planned_output_kg",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                (
                    "actual_output_kg",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "waste_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("8.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "yarn_count",
                    models.CharField(
                        blank=True, help_text="e.g. Ne 30/1", max_length=20
                    ),
                ),
                ("twist_per_meter", models.IntegerField(blank=True, null=True)),
                ("planned_start_date", models.DateTimeField()),
                ("planned_end_date", models.DateTimeField()),
                ("actual_start_date", models.DateTimeField(blank=True, null=True)),
                ("actual_end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("shift_1", "1-smena (08:00-20:00)"),
                            ("shift_2", "2-smena (20:00-08:00)"),
                            ("shift_3", "3-smena"),
                            ("shift_4", "4-smena"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "brigade",
                    models.IntegerField(
                        choices=[
                            (1, "1-brigada"),
                            (2, "2-brigada"),
                            (3, "3-brigada"),
                            (4, "4-brigada"),
                        ]
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_production_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cotton_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_orders",
                        to="cotton_production.cottonbatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "input_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_orders_input",
                        to="warehouse.product",
                    ),
                ),
                (
                    "output_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_orders_output",
                        to="warehouse.product",
                    ),
                ),
                (
                    "production_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="production.productionline",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supervised_production_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tolling_contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_orders",
                        to="tolling.tollingcontract",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "yarn_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_orders",
                        to="yarn_production.yarnbatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ishlab chiqarish buyurtmasi",
                "verbose_name_plural": "Ishlab chiqarish buyurtmalari",
                "db_table": "production_orders",
                "ordering": ["-planned_start_date"],
            },
        ),
        migrations.CreateModel(
            name="ProductionBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "batch_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_production", "Ishlab chiqarilmoqda"),
                            ("qc_pending", "Sifat nazorati kutilmoqda"),
                            ("qc_passed", "Sifat nazoratidan o'tdi"),
                            ("qc_failed", "Sifat nazorati rad etdi"),
                            ("in_stock", "Omborxonada"),
                            ("shipped", "Jo'natildi"),
                        ],
                        default="in_production",
                        max_length=20,
                    ),
                ),
                (
                    "quantity_kg",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                ("yarn_count_actual", models.CharField(blank=True, max_length=20)),
                ("twist_actual", models.IntegerField(blank=True, null=True)),
                (
                    "strength_cn",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Strength in centiNewtons",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "evenness_cv",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Evenness CV%",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("production_date", models.DateField()),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("shift_1", "1-smena (08:00-20:00)"),
                            ("shift_2", "2-smena (20:00-08:00)"),
                            ("shift_3", "3-smena"),
                            ("shift_4", "4-smena"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "brigade",
                    models.IntegerField(
                        choices=[
                            (1, "1-brigada"),
                            (2, "2-brigada"),
                            (3, "3-brigada"),
                            (4, "4-brigada"),
                        ]
                    ),
                ),
                ("machine_number", models.CharField(blank=True, max_length=50)),
                ("warehouse_location", models.CharField(blank=True, max_length=100)),
                ("pallet_number", models.CharField(blank=True, max_length=50)),
                ("qc_checked_at", models.DateTimeField(blank=True, null=True)),
                ("qc_notes", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "output_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_batches",
                        to="warehouse.product",
                    ),
                ),
                (
                    "qc_checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qc_checked_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="production.productionorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ishlab chiqarish partiyasi",
                "verbose_name_plural": "Ishlab chiqarish partiyalari",
                "db_table": "production_batches",
                "ordering": ["-production_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductionShiftReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "report_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("shift_date", models.DateField(db_index=True)),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("shift_1", "1-smena (08:00-20:00)"),
                            ("shift_2", "2-smena (20:00-08:00)"),
                            ("shift_3", "3-smena"),
                            ("shift_4", "4-smena"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "brigade",
                    models.IntegerField(
                        choices=[
                            (1, "1-brigada"),
                            (2, "2-brigada"),
                            (3, "3-brigada"),
                            (4, "4-brigada"),
                        ]
                    ),
                ),
                ("workers_count", models.PositiveIntegerField(default=1)),
                (
                    "total_input_kg",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "total_output_kg",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "waste_kg",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "planned_runtime_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("12"), max_digits=5
                    ),
                ),
                (
                    "actual_runtime_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "downtime_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                ("downtime_reason", models.TextField(blank=True)),
                (
                    "electricity_kwh",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "gas_m3",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "water_m3",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("defect_count", models.PositiveIntegerField(default=0)),
                ("defect_description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qoralama"),
                            ("submitted", "Topshirilgan"),
                            ("approved", "Tasdiqlangan"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shift_reports_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "production_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_reports",
                        to="production.productionline",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_reports_supervised",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Smena xisoboti",
                "verbose_name_plural": "Smena xisobotlari",
                "db_table": "production_shift_reports",
                "ordering": ["-shift_date", "shift"],
            },
        ),
        migrations.AddIndex(
            model_name="productionorder",
            index=models.Index(fields=["status"], name="production__status_ccd812_idx"),
        ),
        migrations.AddIndex(
            model_name="productionorder",
            index=models.Index(
                fields=["order_type"], name="production__order_t_7e5861_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionorder",
            index=models.Index(
                fields=["planned_start_date"], name="production__planned_30ab96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionbatch",
            index=models.Index(
                fields=["batch_number"], name="production__batch_n_e3235b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionbatch",
            index=models.Index(
                fields=["production_date", "shift"],
                name="production__product_e763f6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productionbatch",
            index=models.Index(fields=["status"], name="production__status_6ca6f2_idx"),
        ),
        migrations.AddIndex(
            model_name="productionshiftreport",
            index=models.Index(
                fields=["shift_date"], name="production__shift_d_09c697_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionshiftreport",
            index=models.Index(fields=["status"], name="production__status_d6a289_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="productionshiftreport",
            unique_together={("production_line", "shift_date", "shift", "brigade")},
        ),
    ]
