import uuid
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("production", "0001_initial"),
        ("warehouse", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityParameter",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("parameter_code", models.CharField(max_length=50, unique=True)),
                ("parameter_name_uz", models.CharField(max_length=200)),
                ("parameter_name_en", models.CharField(max_length=200)),
                ("applies_to", models.CharField(choices=[("raw_cotton", "Xom paxta / Raw Cotton"), ("cotton_fiber", "Paxta tolasi / Cotton Fiber"), ("yarn", "Ip / Yarn"), ("sliver", "Lenta / Sliver")], max_length=20)),
                ("unit", models.CharField(max_length=30)),
                ("data_type", models.CharField(choices=[("numeric", "Raqamli"), ("grade", "Sinf (A/B/C)"), ("pass_fail", "O'tdi/O'tmadi")], max_length=20)),
                ("ozd_standard", models.CharField(blank=True, max_length=100)),
                ("min_value", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("max_value", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("optimal_value", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("testing_method", models.TextField(blank=True)),
                ("equipment_required", models.CharField(blank=True, max_length=200)),
                ("is_critical", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="qualityparameter_created", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="qualityparameter_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "quality_parameters", "ordering": ["applies_to", "parameter_code"], "verbose_name": "Sifat parametri", "verbose_name_plural": "Sifat parametrlari"},
        ),
        migrations.CreateModel(
            name="DefectType",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("defect_code", models.CharField(max_length=50, unique=True)),
                ("defect_name_uz", models.CharField(max_length=200)),
                ("defect_name_en", models.CharField(max_length=200)),
                ("severity", models.CharField(choices=[("critical", "Kritik"), ("major", "Asosiy"), ("minor", "Kichik")], max_length=20)),
                ("applies_to", models.CharField(choices=[("raw_cotton", "Xom paxta / Raw Cotton"), ("cotton_fiber", "Paxta tolasi / Cotton Fiber"), ("yarn", "Ip / Yarn"), ("sliver", "Lenta / Sliver")], max_length=20)),
                ("auto_reject", models.BooleanField(default=False)),
                ("requires_reprocessing", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="defecttype_created", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="defecttype_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "quality_defect_types", "ordering": ["severity", "defect_code"], "verbose_name": "Nuqs turi", "verbose_name_plural": "Nuqs turlari"},
        ),
        migrations.CreateModel(
            name="QualityTest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("test_number", models.CharField(db_index=True, max_length=50, unique=True)),
                ("test_type", models.CharField(choices=[("incoming_raw", "Qabul qilinadigan xom ashyo"), ("in_process", "Jarayon ichida"), ("final_product", "Tayyor mahsulot"), ("periodic", "Davriy tekshiruv")], max_length=20)),
                ("sample_size_kg", models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal("0.001"))])),
                ("sample_location", models.CharField(blank=True, max_length=200)),
                ("sample_taken_date", models.DateTimeField()),
                ("test_date", models.DateTimeField()),
                ("lab_equipment", models.CharField(blank=True, max_length=200)),
                ("overall_result", models.CharField(choices=[("pending", "Kutilmoqda"), ("passed", "O'tdi"), ("failed", "O'tmadi"), ("conditional", "Shartli"), ("retest", "Qayta tekshirish kerak")], default="pending", max_length=20)),
                ("quality_grade", models.CharField(blank=True, max_length=10)),
                ("approved_for_use", models.BooleanField(default=False)),
                ("rejected", models.BooleanField(default=False)),
                ("rejection_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="qualitytest_created", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="qualitytest_updated", to=settings.AUTH_USER_MODEL)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="quality_tests", to="warehouse.product")),
                ("production_batch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="quality_tests", to="production.productionbatch")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tests_reviewed", to=settings.AUTH_USER_MODEL)),
                ("sample_taken_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="samples_taken", to=settings.AUTH_USER_MODEL)),
                ("tested_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="tests_performed", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "quality_tests", "ordering": ["-test_date"], "verbose_name": "Sifat sinovi", "verbose_name_plural": "Sifat sinovlari"},
        ),
        migrations.AddIndex(
            model_name="qualitytest",
            index=models.Index(fields=["test_number"], name="quality_tes_test_nu_idx"),
        ),
        migrations.AddIndex(
            model_name="qualitytest",
            index=models.Index(fields=["test_date", "overall_result"], name="quality_tes_test_da_idx"),
        ),
        migrations.CreateModel(
            name="QualityTestResult",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("measured_value", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("measured_grade", models.CharField(blank=True, max_length=10)),
                ("is_within_spec", models.BooleanField(default=True)),
                ("deviation_percentage", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("instrument_id", models.CharField(blank=True, max_length=50)),
                ("calibration_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("parameter", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="quality.qualityparameter")),
                ("quality_test", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="test_results", to="quality.qualitytest")),
            ],
            options={"db_table": "quality_test_results", "verbose_name": "Sinov natijasi", "verbose_name_plural": "Sinov natijalari"},
        ),
        migrations.AddConstraint(
            model_name="qualitytestresult",
            constraint=models.UniqueConstraint(fields=["quality_test", "parameter"], name="unique_test_parameter"),
        ),
        migrations.CreateModel(
            name="QualityCertificate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("certificate_number", models.CharField(db_index=True, max_length=50, unique=True)),
                ("quantity_kg", models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.001"))])),
                ("quality_grade", models.CharField(max_length=10)),
                ("complies_with", models.CharField(blank=True, max_length=200)),
                ("issue_date", models.DateField()),
                ("valid_until", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("approved_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="certificates_approved", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="qualitycertificate_created", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="qualitycertificate_updated", to=settings.AUTH_USER_MODEL)),
                ("issued_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="certificates_issued", to=settings.AUTH_USER_MODEL)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="quality_certificates", to="warehouse.product")),
                ("production_batch", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="quality_certificate", to="production.productionbatch")),
                ("quality_test", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="certificates", to="quality.qualitytest")),
            ],
            options={"db_table": "quality_certificates", "ordering": ["-issue_date"], "verbose_name": "Sifat sertifikati", "verbose_name_plural": "Sifat sertifikatlari"},
        ),
        migrations.AddIndex(
            model_name="qualitycertificate",
            index=models.Index(fields=["certificate_number"], name="quality_cer_cert_nu_idx"),
        ),
        migrations.AddIndex(
            model_name="qualitycertificate",
            index=models.Index(fields=["issue_date", "is_active"], name="quality_cer_issue_da_idx"),
        ),
        migrations.CreateModel(
            name="QualityDefect",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("defect_number", models.CharField(db_index=True, max_length=50, unique=True)),
                ("detection_stage", models.CharField(choices=[("production", "Ishlab chiqarishda"), ("qc_inspection", "Sifat nazoratida"), ("packaging", "Qadoqlashda"), ("customer", "Mijoz tomonidan")], max_length=20)),
                ("quantity_affected_kg", models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal("0.001"))])),
                ("percentage_of_batch", models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ("detected_date", models.DateTimeField()),
                ("description", models.TextField(blank=True)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="quality/defects/")),
                ("root_cause", models.TextField(blank=True)),
                ("corrective_action", models.TextField(blank=True)),
                ("preventive_action", models.TextField(blank=True)),
                ("disposition", models.CharField(blank=True, choices=[("use_as_is", "Shundayligicha ishlatish"), ("reprocess", "Qayta ishlash"), ("downgrade", "Sinfni tushirish"), ("scrap", "Chiqindiga chiqarish")], max_length=20)),
                ("status", models.CharField(choices=[("open", "Ochiq"), ("investigating", "Tekshirilmoqda"), ("resolved", "Hal qilindi"), ("closed", "Yopildi")], default="open", max_length=20)),
                ("resolved_date", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="qualitydefect_created", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="qualitydefect_updated", to=settings.AUTH_USER_MODEL)),
                ("defect_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="quality.defecttype")),
                ("detected_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="defects_detected", to=settings.AUTH_USER_MODEL)),
                ("production_batch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quality_defects", to="production.productionbatch")),
                ("resolved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="defects_resolved", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "quality_defects", "ordering": ["-detected_date"], "verbose_name": "Nuqs qayd", "verbose_name_plural": "Nuqs qaydlari"},
        ),
        migrations.AddIndex(
            model_name="qualitydefect",
            index=models.Index(fields=["defect_number"], name="quality_def_defect__idx"),
        ),
        migrations.AddIndex(
            model_name="qualitydefect",
            index=models.Index(fields=["status"], name="quality_def_status_idx"),
        ),
        migrations.AddIndex(
            model_name="qualitydefect",
            index=models.Index(fields=["detected_date"], name="quality_def_detecte_idx"),
        ),
    ]
