# Generated by Django 5.0.6 on 2026-05-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_06c470_idx",
            old_name="notif_recipient_read_created_idx",
        ),
    ]
