# Generated by Django 5.0.6 on 2026-05-19 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={"verbose_name_plural": "product categories"},
        ),
        migrations.AlterModelOptions(
            name="stockledger",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="stockledger",
            name="unique_warehouse_product",
        ),
        migrations.RenameIndex(
            model_name="stockmovement",
            new_name="stock_movem_warehou_bf2a0b_idx",
            old_name="stock_mv_wh_prod_date_idx",
        ),
        migrations.RenameIndex(
            model_name="stockmovement",
            new_name="stock_movem_movemen_06abf8_idx",
            old_name="stock_mv_type_date_idx",
        ),
        migrations.AlterField(
            model_name="product",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="yarn_count",
            field=models.CharField(
                blank=True, help_text="e.g. Ne20/1, Ne30/1", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="yarn_type",
            field=models.CharField(
                blank=True, help_text="Carded / Combed / Compact", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stockledger",
            unique_together={("warehouse", "product")},
        ),
    ]
