import uuid
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("production", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("equipment_code", models.CharField(max_length=50, unique=True)),
                ("equipment_name", models.CharField(max_length=200)),
                ("equipment_type", models.CharField(choices=[("spinning_frame", "Ip yigirish mashinasi"), ("blowroom", "Ochish mashinasi"), ("carding", "Taroq mashina"), ("drawing", "Cho'zish mashina"), ("roving", "Roving mashina"), ("winding", "O'rash mashina"), ("ginning", "Paxta tozalash"), ("utility", "Yordamchi (kompresor, generator)")], max_length=30)),
                ("manufacturer", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("year_manufactured", models.IntegerField(blank=True, null=True)),
                ("rated_capacity", models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),
                ("capacity_unit", models.CharField(default="kg/hour", max_length=20)),
                ("spindles_count", models.IntegerField(blank=True, null=True)),
                ("installation_date", models.DateField(blank=True, null=True)),
                ("warranty_expires", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("maintenance_frequency_days", models.IntegerField(default=30)),
                ("last_maintenance_date", models.DateField(blank=True, null=True)),
                ("next_maintenance_due", models.DateField(blank=True, null=True)),
                ("total_operating_hours", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12)),
                ("status", models.CharField(choices=[("operational", "Ishlamoqda"), ("maintenance", "Ta'mirda"), ("breakdown", "Buzilgan"), ("idle", "Bo'sh turgan"), ("decommissioned", "Foydalanishdan chiqarilgan")], default="operational", max_length=20)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="equipment/photos/")),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="equipment_created", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="equipment_updated", to=settings.AUTH_USER_MODEL)),
                ("production_line", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="equipment", to="production.productionline")),
            ],
            options={"db_table": "maintenance_equipment", "ordering": ["equipment_code"], "verbose_name": "Uskuna", "verbose_name_plural": "Uskunalar"},
        ),
        migrations.AddIndex(model_name="equipment", index=models.Index(fields=["status"], name="maint_equip_status_idx")),
        migrations.AddIndex(model_name="equipment", index=models.Index(fields=["next_maintenance_due"], name="maint_equip_nextmt_idx")),
        migrations.CreateModel(
            name="SparePart",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("part_code", models.CharField(max_length=50, unique=True)),
                ("part_name", models.CharField(max_length=200)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("manufacturer_part_number", models.CharField(blank=True, max_length=100)),
                ("supplier_name", models.CharField(blank=True, max_length=200)),
                ("lead_time_days", models.IntegerField(default=7)),
                ("current_stock", models.IntegerField(default=0)),
                ("unit_of_measure", models.CharField(default="pcs", max_length=20)),
                ("minimum_stock", models.IntegerField(default=1)),
                ("maximum_stock", models.IntegerField(default=10)),
                ("unit_cost_uzs", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12)),
                ("last_purchase_date", models.DateField(blank=True, null=True)),
                ("storage_location", models.CharField(blank=True, max_length=200)),
                ("is_critical", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sparepart_created", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sparepart_updated", to=settings.AUTH_USER_MODEL)),
                ("compatible_equipment", models.ManyToManyField(blank=True, related_name="compatible_parts", to="maintenance.equipment")),
            ],
            options={"db_table": "maintenance_spare_parts", "ordering": ["category", "part_code"], "verbose_name": "Ehtiyot qism", "verbose_name_plural": "Ehtiyot qismlar"},
        ),
        migrations.AddIndex(model_name="sparepart", index=models.Index(fields=["category"], name="maint_spare_cat_idx")),
        migrations.AddIndex(model_name="sparepart", index=models.Index(fields=["is_critical"], name="maint_spare_crit_idx")),
        migrations.CreateModel(
            name="MaintenanceSchedule",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("maintenance_type", models.CharField(choices=[("routine", "Muntazam tekshiruv"), ("preventive", "Profilaktika"), ("overhaul", "Kapital ta'mir"), ("calibration", "Kalibrovka")], max_length=20)),
                ("frequency_days", models.IntegerField()),
                ("estimated_duration_hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("maintenance_checklist", models.TextField(blank=True)),
                ("required_technicians", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="maintenanceschedule_created", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="maintenanceschedule_updated", to=settings.AUTH_USER_MODEL)),
                ("equipment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="schedules", to="maintenance.equipment")),
                ("required_spare_parts", models.ManyToManyField(blank=True, to="maintenance.sparepart")),
            ],
            options={"db_table": "maintenance_schedules", "ordering": ["equipment", "maintenance_type"], "verbose_name": "Ta'mir jadvali", "verbose_name_plural": "Ta'mir jadvallari"},
        ),
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("record_number", models.CharField(db_index=True, max_length=50, unique=True)),
                ("maintenance_type", models.CharField(choices=[("routine", "Muntazam tekshiruv"), ("preventive", "Profilaktika"), ("overhaul", "Kapital ta'mir"), ("calibration", "Kalibrovka")], max_length=20)),
                ("scheduled_date", models.DateField()),
                ("scheduled_duration_hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                ("actual_duration_hours", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("work_description", models.TextField(blank=True)),
                ("checklist_completed", models.TextField(blank=True)),
                ("findings", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("labor_cost_uzs", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12)),
                ("parts_cost_uzs", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12)),
                ("total_cost_uzs", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12)),
                ("status", models.CharField(choices=[("scheduled", "Rejalashtirilgan"), ("in_progress", "Bajarilmoqda"), ("completed", "Yakunlandi"), ("cancelled", "Bekor qilindi")], default="scheduled", max_length=20)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("equipment_status_after", models.CharField(blank=True, choices=[("operational", "Ishlamoqda"), ("maintenance", "Ta'mirda"), ("breakdown", "Buzilgan"), ("idle", "Bo'sh turgan"), ("decommissioned", "Foydalanishdan chiqarilgan")], max_length=20)),
                ("test_run_successful", models.BooleanField(blank=True, null=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="maintenance_approved", to=settings.AUTH_USER_MODEL)),
                ("assigned_technician", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="maintenance_assigned", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="maintenancerecord_created", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="maintenancerecord_updated", to=settings.AUTH_USER_MODEL)),
                ("equipment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="maintenance_records", to="maintenance.equipment")),
            ],
            options={"db_table": "maintenance_records", "ordering": ["-scheduled_date"], "verbose_name": "Ta'mir qaydnomasi", "verbose_name_plural": "Ta'mir qaydnomalari"},
        ),
        migrations.AddIndex(model_name="maintenancerecord", index=models.Index(fields=["record_number"], name="maint_rec_recnum_idx")),
        migrations.AddIndex(model_name="maintenancerecord", index=models.Index(fields=["status"], name="maint_rec_status_idx")),
        migrations.AddIndex(model_name="maintenancerecord", index=models.Index(fields=["scheduled_date"], name="maint_rec_schdate_idx")),
        migrations.CreateModel(
            name="MaintenancePartUsage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("quantity_used", models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("unit_cost_uzs", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_cost_uzs", models.DecimalField(decimal_places=2, max_digits=12)),
                ("removed_part_condition", models.CharField(choices=[("worn", "Eskirgan"), ("broken", "Singan"), ("corroded", "Korroziyaga uchragan"), ("preventive", "Profilaktik almashtirish")], max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("maintenance_record", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="part_usages", to="maintenance.maintenancerecord")),
                ("spare_part", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="maintenance.sparepart")),
            ],
            options={"db_table": "maintenance_part_usage", "verbose_name": "Ehtiyot qism sarflanishi"},
        ),
        migrations.CreateModel(
            name="EquipmentDowntime",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("downtime_number", models.CharField(db_index=True, max_length=50, unique=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("duration_hours", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("downtime_type", models.CharField(choices=[("planned_maintenance", "Rejalashtirilgan ta'mir"), ("unplanned_breakdown", "Kutilmagan buzilish"), ("changeover", "Qayta sozlash"), ("raw_material_shortage", "Xom ashyo yetishmasligi"), ("power_outage", "Elektr uzilishi"), ("operator_break", "Operator tanaffusi"), ("other", "Boshqa")], max_length=30)),
                ("reason", models.TextField()),
                ("problem_description", models.TextField(blank=True)),
                ("production_loss_kg", models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=12)),
                ("financial_loss_uzs", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=15)),
                ("action_taken", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("ongoing", "Davom etmoqda"), ("resolved", "Hal qilindi")], default="ongoing", max_length=20)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="equipmentdowntime_created", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="equipmentdowntime_updated", to=settings.AUTH_USER_MODEL)),
                ("equipment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="downtimes", to="maintenance.equipment")),
                ("maintenance_record", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="maintenance.maintenancerecord")),
                ("reported_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="downtimes_reported", to=settings.AUTH_USER_MODEL)),
                ("resolved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="downtimes_resolved", to=settings.AUTH_USER_MODEL)),
                ("shift_report", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="production.productionshiftreport")),
            ],
            options={"db_table": "maintenance_downtime", "ordering": ["-start_time"], "verbose_name": "To'xtash vaqti", "verbose_name_plural": "To'xtash vaqtlari"},
        ),
        migrations.AddIndex(model_name="equipmentdowntime", index=models.Index(fields=["downtime_number"], name="maint_dt_num_idx")),
        migrations.AddIndex(model_name="equipmentdowntime", index=models.Index(fields=["status"], name="maint_dt_status_idx")),
        migrations.AddIndex(model_name="equipmentdowntime", index=models.Index(fields=["start_time"], name="maint_dt_start_idx")),
        migrations.CreateModel(
            name="OEEMeasurement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("measurement_date", models.DateField(db_index=True)),
                ("shift", models.CharField(max_length=20)),
                ("planned_production_time_hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("downtime_hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("availability_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("target_production_kg", models.DecimalField(decimal_places=3, max_digits=12)),
                ("actual_production_kg", models.DecimalField(decimal_places=3, max_digits=12)),
                ("performance_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("total_production_kg", models.DecimalField(decimal_places=3, max_digits=12)),
                ("defect_production_kg", models.DecimalField(decimal_places=3, max_digits=12)),
                ("quality_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("oee_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                ("equipment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="oee_measurements", to="maintenance.equipment")),
                ("shift_report", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="oee_measurement", to="production.productionshiftreport")),
            ],
            options={"db_table": "maintenance_oee", "ordering": ["-measurement_date", "shift"], "verbose_name": "OEE o'lchovi", "verbose_name_plural": "OEE o'lchovlari"},
        ),
        migrations.AddConstraint(
            model_name="oeemeasurement",
            constraint=models.UniqueConstraint(fields=["equipment", "measurement_date", "shift"], name="unique_oee_equipment_date_shift"),
        ),
    ]
