# Generated by Django 5.0.6 on 2026-05-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("costing_engine", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="costsnapshot",
            new_name="cost_snapsh_stage_189d61_idx",
            old_name="cost_snap_stage_date_idx",
        ),
        migrations.RenameIndex(
            model_name="costsnapshot",
            new_name="cost_snapsh_product_8866de_idx",
            old_name="cost_snap_prod_date_idx",
        ),
    ]
