from __future__ import annotations

import random
from dataclasses import dataclass
from datetime import date, timedelta
from decimal import Decimal, ROUND_HALF_UP
from typing import Iterable, List, Optional, Sequence, Tuple

try:
    from faker import Faker
except ImportError:  # pragma: no cover
    raise ImportError("Faker is required for demo data generation. Install it with `pip install Faker`.")

from core.utils import round_money, round_weight, safe_divide

faker = Faker(["uz_UZ", "ru_RU", "en_US"])

DEMO_MARKER = "demo_seed"
DEMO_NOTE = f"{DEMO_MARKER}: generated by generate_demo_data command"


def seed_rng(seed: Optional[int] = None) -> int:
    if seed is None:
        seed = random.randint(1_000_000, 9_999_999)
    random.seed(seed)
    faker.seed_instance(seed)
    return seed


def decimal(value: float | str | Decimal, places: int = 4) -> Decimal:
    quantize = Decimal("1") if places <= 0 else Decimal("1").scaleb(-places)
    return Decimal(str(value)).quantize(quantize, rounding=ROUND_HALF_UP)


def decimal_weight(value: float | str | Decimal) -> Decimal:
    return decimal(value, places=3)


def decimal_money(value: float | str | Decimal) -> Decimal:
    return decimal(value, places=4)


def business_day_rate(date_value: date, base_rate: Decimal = Decimal("11500")) -> Decimal:
    day_offset = (date_value - date_value.replace(day=1)).days
    drift = Decimal("0.0006") * Decimal(day_offset)
    noise = Decimal(str(random.uniform(-0.5, 0.5))) * Decimal("15")
    rate = base_rate + drift + noise
    return rate.quantize(Decimal("0.0001"), rounding=ROUND_HALF_UP)


def build_usd_uzs_series(start_date: date, days: int) -> list[Tuple[date, Decimal]]:
    rates = []
    current = start_date
    base_rate = Decimal("11500") + Decimal(str(random.uniform(-80, 80)))
    for _ in range(days):
        if current.weekday() >= 5:
            change = Decimal(str(random.uniform(-5, 5)))
        else:
            change = Decimal(str(random.uniform(-25, 25)))
        base_rate = max(10400, base_rate + change)
        rates.append((current, base_rate.quantize(Decimal("0.0001"), rounding=ROUND_HALF_UP)))
        current += timedelta(days=1)
    return rates


def select_client_status() -> tuple[str, bool, bool]:
    active = random.random() > 0.15
    debtor = random.random() < 0.25
    return ("active" if active else "inactive", active, debtor)


def choose_contract_share() -> tuple[Decimal, Decimal, Decimal]:
    processor = Decimal(random.choice([50, 55, 60, 65, 70]))
    customer = Decimal(random.choice([25, 30, 35, 40]))
    loss = Decimal("100") - processor - customer
    if loss < 0:
        processor = Decimal("60")
        customer = Decimal("35")
        loss = Decimal("5")
    return processor, customer, loss


def generate_company_name() -> str:
    name = faker.company()
    if random.random() < 0.35:
        suffix = random.choice(["MChJ", "AJ", "LLC", "Masj", "Textile"])
        name = f"{name} {suffix}".strip()
    return name


def generate_phone_number() -> str:
    prefix = random.choice(["+99890", "+99891", "+99893", "+99894", "+99895"])
    return f"{prefix}{random.randint(1000000, 9999999)}"


def is_weekend(dt: date) -> bool:
    return dt.weekday() >= 5


def clamp_decimal(value: Decimal, min_value: Decimal, max_value: Decimal) -> Decimal:
    if value < min_value:
        return min_value
    if value > max_value:
        return max_value
    return value


def generate_invoice_amount(base_amount: Decimal, delivered_qty: Decimal, total_qty: Decimal) -> Decimal:
    if not total_qty or total_qty == Decimal("0"):
        return Decimal("0")
    share = delivered_qty / total_qty
    return round_money(base_amount * share)


def split_amount(total: Decimal, parts: int) -> list[Decimal]:
    if parts <= 1:
        return [total]
    base = (total / parts).quantize(Decimal("0.0001"), rounding=ROUND_HALF_UP)
    result = [base] * parts
    remainder = total - (base * parts)
    for idx in range(len(result)):
        if remainder == Decimal("0"):
            break
        result[idx] += Decimal("0.0001")
        remainder -= Decimal("0.0001")
    return result


def generate_local_address() -> str:
    region = random.choice([
        "Tashkent", "Samarqand", "Buxoro", "Nukus", "Namangan", "Farg'ona", "Andijon", "Qarshi"
    ])
    street = faker.street_name()
    return f"{street}, {region}, Uzbekistan"


def generate_person_name() -> tuple[str, str]:
    full = faker.name()
    parts = full.split()
    if len(parts) >= 2:
        return parts[0], " ".join(parts[1:])
    return full, ""


def hourly_efficiency(hour_target: float = 8.0) -> tuple[Decimal, Decimal]:
    actual = Decimal(str(random.uniform(hour_target - 1.5, hour_target + 0.5))).quantize(Decimal("0.01"))
    downtime = Decimal(str(random.randint(0, 50)))
    return actual, downtime


def qty_from_weight(base_kg: Decimal, variation: float = 0.12) -> Decimal:
    return decimal_weight(base_kg * Decimal(str(random.uniform(1 - variation, 1 + variation))))


def choose_production_loss() -> Decimal:
    return decimal(str(random.uniform(3.0, 8.0)), places=2)


def day_sequence(start_date: date, days: int) -> Iterable[date]:
    current = start_date
    for _ in range(days):
        yield current
        current += timedelta(days=1)


def choose_vendor_name() -> str:
    return generate_company_name()


def choose_payment_method() -> str:
    return random.choice(["cash", "bank_transfer", "USD", "UZS"])


def choose_expense_category() -> str:
    return random.choice([
        "raw_material_purchase", "utility_expense", "salary_expense",
        "maintenance_expense", "logistics", "other_expense",
    ])


def select_invoice_payment_status(amount_due: Decimal, paid: Decimal) -> str:
    if paid >= amount_due:
        return "paid"
    if paid > Decimal("0"):
        return "partially_paid"
    return "issued"


def select_batch_status(batch_date: date, today: date) -> str:
    if batch_date < today - timedelta(days=14):
        return "completed"
    if batch_date < today - timedelta(days=3):
        return "in_progress"
    return "draft"


def random_choice_weighted(choices: Sequence[tuple[str, float]]) -> str:
    names, weights = zip(*choices)
    return random.choices(names, weights=weights, k=1)[0]
